spring:
  application:
    name: airelm
  datasource:
    url: jdbc:postgresql://localhost:5432/progitest
    username: postgres
    password: postgrestest
  jpa:
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${PORT:8780}

