spring:
  application:
    name: airelm
  datasource:
    url: jdbc:postgresql://localhost:5432/ems_db
    username: postgres
    password: testiramo123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv23li1gWJTtMJqM6Ptb
            client-secret: 5a7363806dec87163bdf8bedd2b57303125af82b
            scope: user, user:email

server:
  port: ${PORT:8780}
