spring:
  application:
    name: airelm
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${env.CLIENT-ID}
            client-secret: ${env.CLIENT-SERVER}

       jpa:
        hibernate:
         naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        ddl-auto: none
      properties:
       hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

    datasource:
     url: jdbc:postgresql://localhost:5432/progitest
    username: postgres
    password: postgrestest

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liiGhr0oNEtx5CtQ
            client-secret: 3a1a8ef0306befcc98e1d35981601b6eb7957ce4


server:
  port: ${PORT:8780}

