spring:
  application:
    name: airelm
  datasource:
    url: jdbc:postgresql://localhost:5432/ems_db
    username: postgres
    password: testiramo123
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: user, email

server:
  port: ${PORT:8780}