spring:
  application:
    name: airelm
  datasource:
    url: jdbc:postgresql://localhost:5432/PROGI
    username: postgres
    password: testiranje123
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23lix0IjEi7CKwyNQg
            client-secret: 889926092718db2f044a0c61047ae4e8101d8f3b
            scope: user, user:email

server:
  port: ${PORT:8780}
