spring:
  application:
    name: airelm
  datasource:
    url: jdbc:postgresql://localhost:5432/ems_db
    username: postgres
    password: testiramo123
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${env.CLIENT_ID}
            client-secret: ${env.CLIENT_SECRET}
            scope: user, user:email

       jpa:
        hibernate:
         naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        ddl-auto: none
      properties:
       hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

    datasource:
     url: jdbc:postgresql://localhost:5432/progitest
    username: postgres
    password: postgrestest

server:
  port: ${PORT:8780}

