name: Build and Push API

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
  workflow_dispatch:

jobs:
  build-and-push-api:
    name: Build and Push API
    runs-on: 'ubuntu-latest'
    env:
      API_DEPLOY_HOOK: ${{ secrets.API_DEPLOY_HOOK }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: 'gradle'
          cache-dependency-path: |
            api/*.gradle*
            api/**/gradle-wrapper.properties

      - name: Gradle build
        run: ./gradlew bootJar --no-daemon
        working-directory: api

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          target: 'github-actions-api'
          context: api
          push: true
          tags: 'ghcr.io/${{ github.repository }}/api.relm:latest'

      - name: Trigger release
        if: '${{ env.API_DEPLOY_HOOK }}'
        run: 'curl ${{ env.API_DEPLOY_HOOK }}'
